[project]
name = "reinforcedintro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.5.0",
    "matplotlib>=3.10.6",
    "pygame>=2.6.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
